<?php
require_once __DIR__ . '/../../includes/layout.php';

$menu = [
    ['label' => 'Delegation Reports', 'href' => 'delegation_reports.php'],
    ['label' => 'Auto Delegation', 'href' => 'delegation_auto.php'],
    ['label' => 'Manual Delegation', 'href' => 'delegation_manual.php'],
    ['label' => 'Verifier Delegated List', 'href' => 'delegation_verifier_list.php'],
    ['label' => 'Candidate Delegated List', 'href' => 'delegation_candidate_list.php'],
];

ob_start();
?>
<div class="card">
    <h3>All Delegation Reports</h3>
    <p class="card-subtitle">Generate reports for candidate-wise component delegation (UI only).</p>

    <form class="form-grid" style="margin-top:14px;">
        <div class="form-control">
            <label>Customer</label>
            <select>
                <option>All Customers</option>
                <option>Sample Client</option>
            </select>
        </div>
        <div class="form-control">
            <label>Job Role</label>
            <select>
                <option>All Job Roles</option>
                <option>Operations</option>
            </select>
        </div>
        <div class="form-control">
            <label>From Date</label>
            <input type="date">
        </div>
        <div class="form-control">
            <label>To Date</label>
            <input type="date">
        </div>
        <div class="form-control">
            <label>Status (Delegation List)</label>
            <select>
                <option>All</option>
                <option>Delegated</option>
                <option>Pending</option>
            </select>
        </div>
        <div class="form-control">
            <label>Component</label>
            <select>
                <option>All Components</option>
                <option>World Check</option>
                <option>Employer 1</option>
            </select>
        </div>
        <div class="form-control">
            <label>Report Style</label>
            <select>
                <option>Multiple Rows</option>
                <option>Single Row</option>
            </select>
        </div>
    </form>
    <div class="form-actions">
        <button type="button" class="btn">Generate (UI only)</button>
        <button type="button" class="btn-secondary btn" style="margin-left:8px;">Download</button>
    </div>

    <table class="table" style="margin-top:18px;">
        <thead>
        <tr>
            <th>Report Name</th>
            <th>Customer</th>
            <th>Job Role</th>
            <th>From</th>
            <th>To</th>
            <th>Generated Date</th>
            <th>Generated By</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>All Delegation Report - Sample</td>
            <td>Sample Client</td>
            <td>Operations</td>
            <td>2025-11-01</td>
            <td>2025-11-24</td>
            <td>2025-11-24</td>
            <td>Work Allocator</td>
        </tr>
        </tbody>
    </table>
</div>
<?php
$content = ob_get_clean();
render_layout('Delegation Reports', 'Work Allocator', $menu, $content);
